version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    network_mode: bridge
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DEFAULT_SQLDB_PASS}
    volumes:
      - /home/${USER}/mysql:/var/lib/mysql
